---
- name: Get info about running services
  service_facts:

- name: Disable systemd-resolved's DNSStubResolver
  include_tasks: disable_dnsstubresolver.yml
  when: >-
    adguardhome_disable_systemd_dnsstubresolver and
    ansible_facts.services
    .get("systemd-resolved.service", {})
    .get("state") == "running"

- name: Install systemd service
  template:
    src: adguardhome.service.j2
    dest: "/etc/systemd/system/{{ adguardhome_service_name }}.service"
    mode: "0664"
  register: adguardhome_systemd_unit
  notify:
    - reload systemd daemon
    - restart adguardhome

- name: Stop adguardhome prior modifying the config. file
  service:
    name: "{{ adguardhome_service_name }}"
    state: stopped

- name: Apply configuration settings
  template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"

- name: Start adguardhome after modifying the config. file
  service:
    name: "{{ adguardhome_service_name }}"
    state: started

- name: Ensure service is enabled
  service:
    name: "{{ adguardhome_service_name }}"
    enabled: yes
