---
- name: reload systemd daemon
  systemd:
    daemon_reload: true

- name: restart adguardhome
  service:
    name: "{{ adguardhome_service_name }}"
    state: restarted
  when: adguardhome_service_start
