---
- name: reload systemd daemon
  systemd:
    daemon_reload: true

- name: restart adguardhome
  service:
    name: "{{ adguardhome_service_name }}"
    state: restarted
  when: adguardhome_service_start

- name: apply adguardhome configuration settings
  template:
    src: adguardhome.yml.j2
    dest: "{{ adguardhome_config_file }}"
    mode: 0644
    owner: "{{ adguardhome_user }}"
    group: "{{ adguardhome_user }}"

- name: stop adguardhome service
  service:
    name: "{{ adguardhome_service_name }}"
    state: stopped

- name: start && enable adguardhome service
  service:
    name: "{{ adguardhome_service_name }}"
    state: started
    enabled: yes
